# Generated by Django 5.0.1 on 2026-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RgbPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('component_name', models.CharField(default='RgbLed', max_length=100)),
                ('preset_name', models.CharField(max_length=100)),
                ('effect_type', models.CharField(choices=[('solid', 'Solid Color'), ('rainbow', 'Rainbow'), ('breathing', 'Breathing'), ('chase', 'Chase'), ('off', 'Off'), ('custom', 'Custom/Manual')], default='custom', max_length=20)),
                ('effect_params', models.JSONField(blank=True, default=dict)),
                ('loop', models.BooleanField(default=True)),
                ('frame_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_id', 'preset_name'],
                'unique_together': {('device_id', 'component_name', 'preset_name')},
            },
        ),
    ]
